param(
    [ValidateSet("staging", "production", "all")]
    [string]$Environment = "all"
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$distDir = Join-Path $repoRoot "dist"

$frontendRoots = @(
    "index.html",
    "404.html",
    "_redirects",
    "assets",
    "components",
    "css",
    "js",
    "Picture",
    "products",
    "views"
)

$unusedLargeOriginals = @(
    "Picture\home\HomePageBackground_1.jpg",
    "Picture\home\HomePageBackground_2.png",
    "Picture\products\voltrix\summerhouse\summerhouse01.jpg",
    "Picture\products\voltrix\summerhouse\summerhouse02.jpg",
    "Picture\products\voltrix\summerhouse\summerhouse03.jpg",
    "Picture\products\voltrix\summerhouse\summerhouse04.jpg",
    "Picture\products\voltdock\voltdock05.jpg",
    "Picture\products\voltdock\voltdock06.jpg",
    "Picture\products\voltdock\voltdock07.jpg",
    "Picture\products\voltdock\voltdock08.jpg",
    "Picture\products\voltdock\voltdock09.jpg",
    "Picture\products\voltdock\voltdock10.jpg",
    "Picture\products\voltrix\voltrix06.jpg"
)

$configs = @{
    staging = @{
        ApiBaseUrl = "https://staging-api.alvatechnology.se"
        VendureShopApi = "https://staging-api.alvatechnology.se/shop-api"
        StripePublishableKey = ""
    }
    production = @{
        ApiBaseUrl = "https://api.alvatechnology.se"
        VendureShopApi = "https://api.alvatechnology.se/shop-api"
        StripePublishableKey = ""
    }
}

function Escape-JsString {
    param([string]$Value)

    return ($Value -replace "\\", "\\" -replace '"', '\"')
}

function Write-RuntimeConfig {
    param(
        [string]$StageDir,
        [string]$Name,
        [hashtable]$Config
    )

    $configPath = Join-Path $StageDir "js\config.js"
    $apiBaseUrl = Escape-JsString $Config.ApiBaseUrl
    $vendureShopApi = Escape-JsString $Config.VendureShopApi
    $stripePublishableKey = Escape-JsString $Config.StripePublishableKey

    $content = @"
// Generated by scripts/package-frontend.ps1 for $Name.
// Do not put backend secrets in this file.
window.ALVA_API_BASE_URL = "$apiBaseUrl";
window.ALVA_VENDURE_SHOP_API = "$vendureShopApi";
window.ALVA_STRIPE_PUBLISHABLE_KEY = "$stripePublishableKey";
"@

    Set-Content -LiteralPath $configPath -Value $content -Encoding UTF8
}

function Remove-IfInside {
    param(
        [string]$BaseDir,
        [string]$TargetPath
    )

    if (-not (Test-Path -LiteralPath $TargetPath)) {
        return
    }

    $baseFullPath = (Resolve-Path -LiteralPath $BaseDir).Path
    $targetFullPath = (Resolve-Path -LiteralPath $TargetPath).Path

    if (-not $targetFullPath.StartsWith($baseFullPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to remove path outside package staging directory: $targetFullPath"
    }

    Remove-Item -LiteralPath $targetFullPath -Recurse -Force
}

function New-FrontendPackage {
    param([string]$Name)

    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $stageDir = Join-Path $distDir "frontend-$Name-$timestamp"
    $zipPath = Join-Path $distDir "alvatech-frontend-$Name-1panel-$timestamp.zip"

    New-Item -ItemType Directory -Force -Path $distDir | Out-Null
    New-Item -ItemType Directory -Force -Path $stageDir | Out-Null

    foreach ($root in $frontendRoots) {
        $source = Join-Path $repoRoot $root
        if (-not (Test-Path -LiteralPath $source)) {
            throw "Missing frontend package source: $root"
        }

        Copy-Item -LiteralPath $source -Destination $stageDir -Recurse -Force
    }

    Get-ChildItem -Path $stageDir -Recurse -Force -Filter ".DS_Store" |
        ForEach-Object { Remove-IfInside -BaseDir $stageDir -TargetPath $_.FullName }

    foreach ($relativePath in $unusedLargeOriginals) {
        Remove-IfInside -BaseDir $stageDir -TargetPath (Join-Path $stageDir $relativePath)
    }

    Write-RuntimeConfig -StageDir $stageDir -Name $Name -Config $configs[$Name]

    $manifest = @"
Package: alvatech frontend
Environment: $Name
Created: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz")
API base URL: $($configs[$Name].ApiBaseUrl)
Vendure Shop API: $($configs[$Name].VendureShopApi)
"@
    Set-Content -LiteralPath (Join-Path $stageDir "package-info.txt") -Value $manifest -Encoding UTF8

    Compress-FrontendArchive -SourceDir $stageDir -DestinationPath $zipPath
    Remove-IfInside -BaseDir $distDir -TargetPath $stageDir

    $zip = Get-Item -LiteralPath $zipPath
    [pscustomobject]@{
        Environment = $Name
        Path = $zip.FullName
        SizeMB = [math]::Round($zip.Length / 1MB, 2)
    }
}

function Compress-FrontendArchive {
    param(
        [string]$SourceDir,
        [string]$DestinationPath
    )

    Add-Type -AssemblyName System.IO.Compression
    Add-Type -AssemblyName System.IO.Compression.FileSystem

    if (Test-Path -LiteralPath $DestinationPath) {
        Remove-Item -LiteralPath $DestinationPath -Force
    }

    $sourceFullPath = (Resolve-Path -LiteralPath $SourceDir).Path
    $zip = [System.IO.Compression.ZipFile]::Open($DestinationPath, [System.IO.Compression.ZipArchiveMode]::Create)

    try {
        Get-ChildItem -LiteralPath $sourceFullPath -Recurse -File | ForEach-Object {
            $relativePath = $_.FullName.Substring($sourceFullPath.Length).TrimStart("\", "/")
            $entryName = $relativePath -replace "\\", "/"

            [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
                $zip,
                $_.FullName,
                $entryName,
                [System.IO.Compression.CompressionLevel]::Optimal
            ) | Out-Null
        }
    } finally {
        $zip.Dispose()
    }
}

$targets = if ($Environment -eq "all") {
    @("staging", "production")
} else {
    @($Environment)
}

$results = foreach ($target in $targets) {
    New-FrontendPackage -Name $target
}

$results | Format-Table -AutoSize
