const SELECTION_KEY='alva-fieldpack-packs';
function selectedCount(){try{const value=sessionStorage.getItem(SELECTION_KEY);return ['0','1','2'].includes(value)?Number(value):0;}catch{return 0;}}
function enquiry(lang,count){const sv=lang==='sv';return '/views/b2b.html?context=fieldpack&request='+encodeURIComponent((sv?'Jag vill ha en offert för ':'I would like a quotation for ')+(count===0?(sv?'FieldPack utan batterier. Jag har redan kompatibla Battery Packs.':'FieldPack without batteries. I already have compatible Battery Packs.'):`FieldPack + ${count} Battery Pack${count>1?'s':''}.`));}
export function renderFieldPackOptions(lang){
 const sv=lang==='sv', count=selectedCount();
 const options=sv?[['FieldPack','Jag har redan kompatibla Battery Packs'],['+ 1 Battery Pack','1 kWh nominell lagring'],['+ 2 Battery Packs','2 kWh nominell lagring']]:[['FieldPack','I already have compatible Battery Packs'],['+ 1 Battery Pack','1 kWh nominal storage'],['+ 2 Battery Packs','2 kWh nominal storage']];
 return `<section class="detail-section fieldpack-options" id="fieldpack-options"><span class="eyebrow">${sv?'VÄLJ DIN SETUP':'CHOOSE YOUR SETUP'}</span><h2>${sv?'Hur många batterier behöver du?':'How many batteries do you need?'}</h2><fieldset class="fieldpack-choice"><legend>${sv?'FieldPack med eller utan Battery Packs':'FieldPack with or without Battery Packs'}</legend><div class="fieldpack-choice__options">${options.map(([title,body],i)=>`<label><input type="radio" name="fieldpack-packs" value="${i}" ${i===count?'checked':''}><span><strong>${title}</strong><small>${body}</small></span></label>`).join('')}</div></fieldset><div class="refined-actions"><a class="button button--primary" data-fieldpack-quote href="${enquiry(lang,count)}">${sv?'Begär offert':'Request quote'}</a><a class="text-link" href="/views/solution-marine.html">${sv?'FieldPack på och vid vattnet':'FieldPack on shore and aboard'} →</a></div><p class="fieldpack-choice__note">${sv?'Alva bekräftar kompatibilitet, kablar och vad som ingår i offerten.':'Alva confirms compatibility, cables and included items in your quotation.'}</p></section>`;
}
export function bindFieldPackOptions(lang){document.querySelectorAll('[name="fieldpack-packs"]').forEach(input=>input.addEventListener('change',()=>{const count=Number(input.value);try{sessionStorage.setItem(SELECTION_KEY,String(count));}catch{}const quote=document.querySelector('[data-fieldpack-quote]');if(quote)quote.href=enquiry(lang,count);}));}
